{{- if .Values.deployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "specific.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- include "specific.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        {{- if .Values.containers }}
        {{- range $i, $c := .Values.containers }}
        - name: {{ default $.Values.name $c.name }}
          image: "{{ coalesce ($c.image.name | default $.Values.image.name) }}:{{ default $.Values.image.tag $c.image.tag }}"
          imagePullPolicy: {{ default "Always" $c.imagePullPolicy }}
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: {{ default $.Values.securityContext.readOnlyRootFilesystem (and $c.securityContext $c.securityContext.readOnlyRootFilesystem) }}
            {{- with $c.securityContext }}
            {{- with .runAsUser }}
            runAsUser: {{ . }}
            {{- end }}
            {{- with .runAsGroup }}
            runAsGroup: {{ . }}
            {{- end }}
            {{- end }}          {{- with $c.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- else }}
          resources:
            {{- $.Values.resources | toYaml | nindent 12 }}
          {{- end }}
          {{- with $c.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $c.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $c.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $c.volumeMounts }}
          volumeMounts:
            {{- toYaml $c.volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if and .Values.volumes .Values.pvc.enabled }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
{{- end }}
