name: Helm Chart CI

on:
  push:
    paths:
      - 'helm-chart/**'
      - '.github/workflows/link-helmchart.yml'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install helm and unittest plugin
        run: |
          HELM_VERSION="v3.18.3"
          HELM_SHA256="6ec85f306dd8fe9eb05c61ba4593182b2afcfefb52f21add3fe043ebbdc48e39"
          HELM_UNITTEST_PLUGIN_VERSION="0.8.2"
          HELM_UNITTEST_PLUGIN_SHA256="b94e638e72cf00034654b70944c0d20cb5d0c3cf"
          curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
          echo "${HELM_SHA256}  helm.tar.gz" | sha256sum -c -
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          git clone https://github.com/helm-unittest/helm-unittest
          cd helm-unittest
          git checkout ${HELM_UNITTEST_PLUGIN_SHA256}
          helm plugin install .
          rm -rf linux-amd64 helm-unittest helm.tar.gz

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run helm lint
        run: |
          helm lint helm-chart/

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs . --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs . --target-branch ${{ github.event.repository.default_branch }}

      - name: Run unit tests
        run: |
          helm unittest helm-chart
