name: Lint and test Helm Chart

on:
  push:
    paths:
      - 'helm-chart/**'
      - '.github/workflows/*.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install helm and unittest plugin
        run: |
          HELM_VERSION="3.18.4-1"
          HELM_UNITTEST_PLUGIN_VERSION="0.8.2"
          HELM_UNITTEST_PLUGIN_SHA256="b94e638e72cf00034654b70944c0d20cb5d0c3cf"
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt update && sudo apt install -y helm=${HELM_VERSION}
          git clone https://github.com/helm-unittest/helm-unittest
          cd helm-unittest
          git checkout ${HELM_UNITTEST_PLUGIN_SHA256}
          helm plugin install .
          rm -rf helm-unittest

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run helm lint
        run: |
          helm lint helm-chart/

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs . --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs . --target-branch ${{ github.event.repository.default_branch }}

      - name: Run unit tests
        run: |
          helm unittest helm-chart
